//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSModel.DB.SMSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Shifts = new HashSet<Shift>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public int TerritoryID { get; set; }
        public int ShopID { get; set; }
        public string 姓 { get; set; }
        public string 名 { get; set; }
        public bool 性別 { get; set; }
        public System.DateTime 生年月日 { get; set; }
        public string 郵便番号 { get; set; }
        public string 住所 { get; set; }
        public string 自宅電話番号 { get; set; }
        public string 携帯電話番号 { get; set; }
        public string Eメールアドレス { get; set; }
        public string 携帯メールアドレス { get; set; }
        public string ホームページ { get; set; }
        public string 備考 { get; set; }
        public System.DateTime 登録日時 { get; set; }
        public bool 外国人フラグ { get; set; }
        public bool 削除フラグ { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Status Status { get; set; }
        public virtual Territory Territory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
